# Form implementation generated from reading ui file 'D:\TMĐT HK6\4.Machine learning\MLBA_FinalProjectt\final_ml\ui\EditModelDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(418, 264)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 101, 21))
        self.label.setObjectName("label")
        self.lineEditName = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditName.setGeometry(QtCore.QRect(140, 20, 241, 20))
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditAccuracy = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditAccuracy.setGeometry(QtCore.QRect(140, 60, 241, 20))
        self.lineEditAccuracy.setObjectName("lineEditAccuracy")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 101, 21))
        self.label_2.setObjectName("label_2")
        self.lineEditPath = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditPath.setGeometry(QtCore.QRect(140, 100, 241, 20))
        self.lineEditPath.setObjectName("lineEditPath")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 101, 21))
        self.label_3.setObjectName("label_3")
        self.btnSave = QtWidgets.QPushButton(parent=Dialog)
        self.btnSave.setGeometry(QtCore.QRect(140, 190, 75, 23))
        self.btnSave.setObjectName("btnSave")
        self.btnCancel = QtWidgets.QPushButton(parent=Dialog)
        self.btnCancel.setGeometry(QtCore.QRect(260, 190, 75, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.lineEditCreatedAt = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditCreatedAt.setGeometry(QtCore.QRect(140, 140, 241, 20))
        self.lineEditCreatedAt.setObjectName("lineEditCreatedAt")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 140, 101, 21))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Chỉnh sửa mô hình"))
        self.label.setText(_translate("Dialog", "Tên mô hình:"))
        self.label_2.setText(_translate("Dialog", "Độ chính xác:"))
        self.label_3.setText(_translate("Dialog", "Đường dẫn:"))
        self.btnSave.setText(_translate("Dialog", "Lưu"))
        self.btnCancel.setText(_translate("Dialog", "Hủy"))
        self.label_4.setText(_translate("Dialog", "Ngày tạo:"))
