# Form implementation generated from reading ui file 'D:\TMĐT HK6\4.Machine learning\MLBA_FinalProjectt\final_ml\ui\ui_admin_user_management.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_UserManagement(object):
    def setupUi(self, MainWindow_UserManagement):
        MainWindow_UserManagement.setObjectName("MainWindow_UserManagement")
        MainWindow_UserManagement.resize(798, 279)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_UserManagement)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutToolbar = QtWidgets.QHBoxLayout()
        self.layoutToolbar.setObjectName("layoutToolbar")
        self.txtSearchUser = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtSearchUser.setObjectName("txtSearchUser")
        self.layoutToolbar.addWidget(self.txtSearchUser)
        self.comboRoleFilter = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboRoleFilter.setObjectName("comboRoleFilter")
        self.comboRoleFilter.addItem("")
        self.comboRoleFilter.addItem("")
        self.comboRoleFilter.addItem("")
        self.layoutToolbar.addWidget(self.comboRoleFilter)
        self.btnAddUser = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAddUser.setObjectName("btnAddUser")
        self.layoutToolbar.addWidget(self.btnAddUser)
        self.btnEditUser = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEditUser.setObjectName("btnEditUser")
        self.layoutToolbar.addWidget(self.btnEditUser)
        self.btnDeleteUser = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDeleteUser.setObjectName("btnDeleteUser")
        self.layoutToolbar.addWidget(self.btnDeleteUser)
        self.btnResetPassword = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnResetPassword.setObjectName("btnResetPassword")
        self.layoutToolbar.addWidget(self.btnResetPassword)
        self.verticalLayout.addLayout(self.layoutToolbar)
        self.tblUsers = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tblUsers.setObjectName("tblUsers")
        self.tblUsers.setColumnCount(6)
        self.tblUsers.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblUsers.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblUsers.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblUsers.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblUsers.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblUsers.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblUsers.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.tblUsers)
        MainWindow_UserManagement.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow_UserManagement)
        self.statusbar.setObjectName("statusbar")
        MainWindow_UserManagement.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_UserManagement)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_UserManagement)

    def retranslateUi(self, MainWindow_UserManagement):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_UserManagement.setWindowTitle(_translate("MainWindow_UserManagement", "Fruit ML - User Management"))
        MainWindow_UserManagement.setStyleSheet(_translate("MainWindow_UserManagement", "\n"
"    * { font-family: \"Segoe UI\"; }\n"
"    QMainWindow { background: #f7f9fb; }\n"
"    QGroupBox { border: 1px solid #e1e5ea; border-radius: 8px; margin-top: 16px; }\n"
"    QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top left; padding: 4px 8px; color: #0b6d77; font-weight: 600; }\n"
"    QPushButton { padding: 8px 14px; border-radius: 6px; border: 1px solid #2aa1a6; background: #2aa1a6; color: white; }\n"
"    QPushButton:hover { background: #238a8f; }\n"
"    QPushButton#btnLogout { background: #f44336; border-color: #f44336; }\n"
"    QLineEdit, QComboBox, QDateEdit, QTextEdit { border: 1px solid #cfd8dc; border-radius: 6px; padding: 6px 8px; background: white; }\n"
"    QTabBar::tab { padding: 8px 14px; border: 1px solid #cfd8dc; border-bottom: none; background: #f1f5f8; border-top-left-radius: 6px; border-top-right-radius: 6px; }\n"
"    QTabBar::tab:selected { background: white; color: #0b6d77; font-weight: 600; }\n"
"    QHeaderView::section { background:#e9f2f3; padding: 6px; border: none; border-right:1px solid #d7e3e4; }\n"
"    QTableView { gridline-color:#e3ecee; selection-background-color:#b2ebf2; selection-color:#003b40; }\n"
"    "))
        self.txtSearchUser.setPlaceholderText(_translate("MainWindow_UserManagement", "Tìm kiếm người dùng..."))
        self.comboRoleFilter.setItemText(0, _translate("MainWindow_UserManagement", "Tất cả"))
        self.comboRoleFilter.setItemText(1, _translate("MainWindow_UserManagement", "User"))
        self.comboRoleFilter.setItemText(2, _translate("MainWindow_UserManagement", "Admin"))
        self.btnAddUser.setText(_translate("MainWindow_UserManagement", "➕ Thêm"))
        self.btnEditUser.setText(_translate("MainWindow_UserManagement", "📝 Sửa"))
        self.btnDeleteUser.setText(_translate("MainWindow_UserManagement", "❌ Xóa"))
        self.btnResetPassword.setText(_translate("MainWindow_UserManagement", "Làm mới"))
        item = self.tblUsers.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_UserManagement", "ID"))
        item = self.tblUsers.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_UserManagement", "Username"))
        item = self.tblUsers.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_UserManagement", "Email"))
        item = self.tblUsers.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow_UserManagement", "Role"))
        item = self.tblUsers.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow_UserManagement", "Ngày tạo"))
        item = self.tblUsers.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow_UserManagement", "Mật khẩu"))
