# Form implementation generated from reading ui file 'D:\TMĐT HK6\4.Machine learning\MLBA_FinalProjectt\final_ml\ui\ui_admin_model_management.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_ModelManagement(object):
    def setupUi(self, MainWindow_ModelManagement):
        MainWindow_ModelManagement.setObjectName("MainWindow_ModelManagement")
        MainWindow_ModelManagement.resize(653, 424)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_ModelManagement)
        self.centralwidget.setObjectName("centralwidget")
        self.vlRoot = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vlRoot.setObjectName("vlRoot")
        self.toolbar = QtWidgets.QHBoxLayout()
        self.toolbar.setObjectName("toolbar")
        self.txtSearchModel = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtSearchModel.setObjectName("txtSearchModel")
        self.toolbar.addWidget(self.txtSearchModel)
        self.btnAddModel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAddModel.setObjectName("btnAddModel")
        self.toolbar.addWidget(self.btnAddModel)
        self.btnEditModel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEditModel.setObjectName("btnEditModel")
        self.toolbar.addWidget(self.btnEditModel)
        self.btnDeleteModel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDeleteModel.setObjectName("btnDeleteModel")
        self.toolbar.addWidget(self.btnDeleteModel)
        self.btnRefreshModels = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnRefreshModels.setObjectName("btnRefreshModels")
        self.toolbar.addWidget(self.btnRefreshModels)
        self.vlRoot.addLayout(self.toolbar)
        self.tblModels = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tblModels.setObjectName("tblModels")
        self.tblModels.setColumnCount(5)
        self.tblModels.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblModels.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblModels.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblModels.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblModels.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblModels.setHorizontalHeaderItem(4, item)
        self.vlRoot.addWidget(self.tblModels)
        MainWindow_ModelManagement.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow_ModelManagement)
        self.statusbar.setObjectName("statusbar")
        MainWindow_ModelManagement.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_ModelManagement)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_ModelManagement)

    def retranslateUi(self, MainWindow_ModelManagement):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_ModelManagement.setWindowTitle(_translate("MainWindow_ModelManagement", "Fruit ML - Model Management"))
        MainWindow_ModelManagement.setStyleSheet(_translate("MainWindow_ModelManagement", "\n"
"    * { font-family: \"Segoe UI\"; }\n"
"    QMainWindow { background: #f7f9fb; }\n"
"    QGroupBox { border: 1px solid #e1e5ea; border-radius: 8px; margin-top: 16px; }\n"
"    QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top left; padding: 4px 8px; color: #0b6d77; font-weight: 600; }\n"
"    QPushButton { padding: 8px 14px; border-radius: 6px; border: 1px solid #2aa1a6; background: #2aa1a6; color: white; }\n"
"    QPushButton:hover { background: #238a8f; }\n"
"    QPushButton#btnLogout { background: #f44336; border-color: #f44336; }\n"
"    QLineEdit, QComboBox, QDateEdit, QTextEdit { border: 1px solid #cfd8dc; border-radius: 6px; padding: 6px 8px; background: white; }\n"
"    QTabBar::tab { padding: 8px 14px; border: 1px solid #cfd8dc; border-bottom: none; background: #f1f5f8; border-top-left-radius: 6px; border-top-right-radius: 6px; }\n"
"    QTabBar::tab:selected { background: white; color: #0b6d77; font-weight: 600; }\n"
"    QHeaderView::section { background:#e9f2f3; padding: 6px; border: none; border-right:1px solid #d7e3e4; }\n"
"    QTableView { gridline-color:#e3ecee; selection-background-color:#b2ebf2; selection-color:#003b40; }\n"
"    "))
        self.txtSearchModel.setPlaceholderText(_translate("MainWindow_ModelManagement", "Tìm kiếm mô hình..."))
        self.btnAddModel.setText(_translate("MainWindow_ModelManagement", "➕ Thêm mô hình"))
        self.btnEditModel.setText(_translate("MainWindow_ModelManagement", "📝 Sửa"))
        self.btnDeleteModel.setText(_translate("MainWindow_ModelManagement", "❌ Xóa"))
        self.btnRefreshModels.setText(_translate("MainWindow_ModelManagement", "Làm mới"))
        item = self.tblModels.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow_ModelManagement", "ID"))
        item = self.tblModels.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow_ModelManagement", "Tên mô hình"))
        item = self.tblModels.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow_ModelManagement", "Độ chính xác"))
        item = self.tblModels.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow_ModelManagement", "Đường dẫn"))
        item = self.tblModels.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow_ModelManagement", "Ngày tạo"))
