# Form implementation generated from reading ui file 'D:\TMĐT HK6\4.Machine learning\MLBA_FinalProjectt\final_ml\ui\ui_admin_dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_AdminDashboard(object):
    def setupUi(self, MainWindow_AdminDashboard):
        MainWindow_AdminDashboard.setObjectName("MainWindow_AdminDashboard")
        MainWindow_AdminDashboard.resize(471, 375)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_AdminDashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.vlRoot = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vlRoot.setObjectName("vlRoot")
        self.lblHeader = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblHeader.setStyleSheet("QLabel#lblHeader{font-size:21px;font-weight:800;color:#0b6d77;}")
        self.lblHeader.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblHeader.setObjectName("lblHeader")
        self.vlRoot.addWidget(self.lblHeader)
        self.gridNav = QtWidgets.QGridLayout()
        self.gridNav.setObjectName("gridNav")
        self.btnGoUserMgmt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnGoUserMgmt.setMinimumSize(QtCore.QSize(220, 80))
        self.btnGoUserMgmt.setObjectName("btnGoUserMgmt")
        self.gridNav.addWidget(self.btnGoUserMgmt, 0, 0, 1, 1)
        self.btnGoDataMgmt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnGoDataMgmt.setMinimumSize(QtCore.QSize(220, 80))
        self.btnGoDataMgmt.setObjectName("btnGoDataMgmt")
        self.gridNav.addWidget(self.btnGoDataMgmt, 0, 1, 1, 1)
        self.btnGoModelMgmt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnGoModelMgmt.setMinimumSize(QtCore.QSize(220, 80))
        self.btnGoModelMgmt.setObjectName("btnGoModelMgmt")
        self.gridNav.addWidget(self.btnGoModelMgmt, 1, 0, 1, 1)
        self.btnGoStatistics = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnGoStatistics.setMinimumSize(QtCore.QSize(220, 80))
        self.btnGoStatistics.setObjectName("btnGoStatistics")
        self.gridNav.addWidget(self.btnGoStatistics, 1, 1, 1, 1)
        self.btnGoHistory = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnGoHistory.setMinimumSize(QtCore.QSize(220, 80))
        self.btnGoHistory.setObjectName("btnGoHistory")
        self.gridNav.addWidget(self.btnGoHistory, 2, 0, 1, 1)
        self.btnLogout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLogout.setMinimumSize(QtCore.QSize(220, 80))
        self.btnLogout.setObjectName("btnLogout")
        self.gridNav.addWidget(self.btnLogout, 2, 1, 1, 1)
        self.vlRoot.addLayout(self.gridNav)
        MainWindow_AdminDashboard.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow_AdminDashboard)
        self.statusbar.setObjectName("statusbar")
        MainWindow_AdminDashboard.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_AdminDashboard)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_AdminDashboard)

    def retranslateUi(self, MainWindow_AdminDashboard):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_AdminDashboard.setWindowTitle(_translate("MainWindow_AdminDashboard", "Fruit ML - Admin Dashboard"))
        MainWindow_AdminDashboard.setStyleSheet(_translate("MainWindow_AdminDashboard", "\n"
"    * { font-family: \"Segoe UI\"; }\n"
"    QMainWindow { background: #f7f9fb; }\n"
"    QGroupBox { border: 1px solid #e1e5ea; border-radius: 8px; margin-top: 16px; }\n"
"    QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top left; padding: 4px 8px; color: #0b6d77; font-weight: 600; }\n"
"    QPushButton { padding: 8px 14px; border-radius: 6px; border: 1px solid #2aa1a6; background: #2aa1a6; color: white; }\n"
"    QPushButton:hover { background: #238a8f; }\n"
"    QPushButton#btnLogout { background: #f44336; border-color: #f44336; }\n"
"    QLineEdit, QComboBox, QDateEdit, QTextEdit { border: 1px solid #cfd8dc; border-radius: 6px; padding: 6px 8px; background: white; }\n"
"    QTabBar::tab { padding: 8px 14px; border: 1px solid #cfd8dc; border-bottom: none; background: #f1f5f8; border-top-left-radius: 6px; border-top-right-radius: 6px; }\n"
"    QTabBar::tab:selected { background: white; color: #0b6d77; font-weight: 600; }\n"
"    QHeaderView::section { background:#e9f2f3; padding: 6px; border: none; border-right:1px solid #d7e3e4; }\n"
"    QTableView { gridline-color:#e3ecee; selection-background-color:#b2ebf2; selection-color:#003b40; }\n"
"    "))
        self.lblHeader.setText(_translate("MainWindow_AdminDashboard", "<h2>Dashboard (Admin)</h2>"))
        self.btnGoUserMgmt.setText(_translate("MainWindow_AdminDashboard", "Quản lý người dùng"))
        self.btnGoDataMgmt.setText(_translate("MainWindow_AdminDashboard", "Quản lý dữ liệu"))
        self.btnGoModelMgmt.setText(_translate("MainWindow_AdminDashboard", "Quản lý mô hình"))
        self.btnGoStatistics.setText(_translate("MainWindow_AdminDashboard", "Thống kê"))
        self.btnGoHistory.setText(_translate("MainWindow_AdminDashboard", "Lịch sử"))
        self.btnLogout.setText(_translate("MainWindow_AdminDashboard", "Đăng xuất"))
