# Form implementation generated from reading ui file 'C:\Users\PC\Downloads\HK2-2024-2025\ĐẠI HỌC\NĂM 3\HK1_2526\MACHINE LEARNING\ML_Pycharm\final_ml\ui\ui_login_signup.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_LoginSignUp(object):
    def setupUi(self, MainWindow_LoginSignUp):
        MainWindow_LoginSignUp.setObjectName("MainWindow_LoginSignUp")
        MainWindow_LoginSignUp.resize(892, 475)
        MainWindow_LoginSignUp.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: #f7faf7;\n"
"        font-family: \"Segoe UI\";\n"
"        font-size: 11pt;\n"
"    }\n"
"    QLabel#lblTitle {\n"
"        color: #2b6a4b;\n"
"        font-size: 20pt;\n"
"        font-weight: bold;\n"
"    }\n"
"    QTabWidget::pane {\n"
"        border: 2px solid #a3c1a1;\n"
"        border-radius: 8px;\n"
"        background: #ffffff;\n"
"    }\n"
"    QTabBar::tab {\n"
"        background: #e6f2eb;\n"
"        color: #2b6a4b;\n"
"        border: 1px solid #a3c1a1;\n"
"        border-bottom: none;\n"
"        border-radius: 6px 6px 0 0;\n"
"        padding: 6px 20px;\n"
"    }\n"
"    QTabBar::tab:selected {\n"
"        background: #cfe8d6;\n"
"        font-weight: 600;\n"
"    }\n"
"    QLineEdit, QComboBox {\n"
"        border: 1px solid #a3c1a1;\n"
"        border-radius: 6px;\n"
"        padding: 6px;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    QPushButton {\n"
"        background-color: #4caf50;\n"
"        color: white;\n"
"        border-radius: 6px;\n"
"        padding: 8px 0;\n"
"        font-weight: 600;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: #45a049;\n"
"    }\n"
"    QPushButton#btnForgotPassword {\n"
"        color: #388e3c;\n"
"        background: transparent;\n"
"        border: none;\n"
"        text-decoration: underline;\n"
"    }\n"
"    QCheckBox {\n"
"        color: #2e2e2e;\n"
"    }\n"
"    QLabel#lblAuthStatus {\n"
"        color: #d32f2f;\n"
"        font-weight: 600;\n"
"    }\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_LoginSignUp)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.tabAuth = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabAuth.setObjectName("tabAuth")
        self.tabLogin = QtWidgets.QWidget()
        self.tabLogin.setObjectName("tabLogin")
        self.gridLogin = QtWidgets.QGridLayout(self.tabLogin)
        self.gridLogin.setObjectName("gridLogin")
        self.lblUsernameLogin = QtWidgets.QLabel(parent=self.tabLogin)
        self.lblUsernameLogin.setObjectName("lblUsernameLogin")
        self.gridLogin.addWidget(self.lblUsernameLogin, 0, 0, 1, 1)
        self.lineEditLoginUsername = QtWidgets.QLineEdit(parent=self.tabLogin)
        self.lineEditLoginUsername.setObjectName("lineEditLoginUsername")
        self.gridLogin.addWidget(self.lineEditLoginUsername, 0, 1, 1, 1)
        self.lblPasswordLogin = QtWidgets.QLabel(parent=self.tabLogin)
        self.lblPasswordLogin.setObjectName("lblPasswordLogin")
        self.gridLogin.addWidget(self.lblPasswordLogin, 1, 0, 1, 1)
        self.lineEditLoginPassword = QtWidgets.QLineEdit(parent=self.tabLogin)
        self.lineEditLoginPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditLoginPassword.setObjectName("lineEditLoginPassword")
        self.gridLogin.addWidget(self.lineEditLoginPassword, 1, 1, 1, 1)
        self.lblRoleLogin = QtWidgets.QLabel(parent=self.tabLogin)
        self.lblRoleLogin.setObjectName("lblRoleLogin")
        self.gridLogin.addWidget(self.lblRoleLogin, 2, 0, 1, 1)
        self.comboRoleLogin = QtWidgets.QComboBox(parent=self.tabLogin)
        self.comboRoleLogin.setObjectName("comboRoleLogin")
        self.comboRoleLogin.addItem("")
        self.comboRoleLogin.addItem("")
        self.gridLogin.addWidget(self.comboRoleLogin, 2, 1, 1, 1)
        self.chkRemember = QtWidgets.QCheckBox(parent=self.tabLogin)
        self.chkRemember.setObjectName("chkRemember")
        self.gridLogin.addWidget(self.chkRemember, 3, 0, 1, 2)
        self.btnLogin = QtWidgets.QPushButton(parent=self.tabLogin)
        self.btnLogin.setObjectName("btnLogin")
        self.gridLogin.addWidget(self.btnLogin, 4, 0, 1, 1)
        self.btnForgotPassword = QtWidgets.QPushButton(parent=self.tabLogin)
        self.btnForgotPassword.setObjectName("btnForgotPassword")
        self.gridLogin.addWidget(self.btnForgotPassword, 4, 1, 1, 1)
        self.tabAuth.addTab(self.tabLogin, "")
        self.tabSignup = QtWidgets.QWidget()
        self.tabSignup.setObjectName("tabSignup")
        self.gridSignup = QtWidgets.QGridLayout(self.tabSignup)
        self.gridSignup.setObjectName("gridSignup")
        self.lblUsernameSignup = QtWidgets.QLabel(parent=self.tabSignup)
        self.lblUsernameSignup.setObjectName("lblUsernameSignup")
        self.gridSignup.addWidget(self.lblUsernameSignup, 0, 0, 1, 1)
        self.lineEditSignupUsername = QtWidgets.QLineEdit(parent=self.tabSignup)
        self.lineEditSignupUsername.setObjectName("lineEditSignupUsername")
        self.gridSignup.addWidget(self.lineEditSignupUsername, 0, 1, 1, 1)
        self.lblEmailSignup = QtWidgets.QLabel(parent=self.tabSignup)
        self.lblEmailSignup.setObjectName("lblEmailSignup")
        self.gridSignup.addWidget(self.lblEmailSignup, 1, 0, 1, 1)
        self.lineEditSignupEmail = QtWidgets.QLineEdit(parent=self.tabSignup)
        self.lineEditSignupEmail.setObjectName("lineEditSignupEmail")
        self.gridSignup.addWidget(self.lineEditSignupEmail, 1, 1, 1, 1)
        self.lblPasswordSignup = QtWidgets.QLabel(parent=self.tabSignup)
        self.lblPasswordSignup.setObjectName("lblPasswordSignup")
        self.gridSignup.addWidget(self.lblPasswordSignup, 2, 0, 1, 1)
        self.lineEditSignupPassword = QtWidgets.QLineEdit(parent=self.tabSignup)
        self.lineEditSignupPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditSignupPassword.setObjectName("lineEditSignupPassword")
        self.gridSignup.addWidget(self.lineEditSignupPassword, 2, 1, 1, 1)
        self.lblConfirmPassword = QtWidgets.QLabel(parent=self.tabSignup)
        self.lblConfirmPassword.setObjectName("lblConfirmPassword")
        self.gridSignup.addWidget(self.lblConfirmPassword, 3, 0, 1, 1)
        self.lineEditSignupCFPassword = QtWidgets.QLineEdit(parent=self.tabSignup)
        self.lineEditSignupCFPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditSignupCFPassword.setObjectName("lineEditSignupCFPassword")
        self.gridSignup.addWidget(self.lineEditSignupCFPassword, 3, 1, 1, 1)
        self.lblRoleSignup = QtWidgets.QLabel(parent=self.tabSignup)
        self.lblRoleSignup.setObjectName("lblRoleSignup")
        self.gridSignup.addWidget(self.lblRoleSignup, 4, 0, 1, 1)
        self.comboRoleSignup = QtWidgets.QComboBox(parent=self.tabSignup)
        self.comboRoleSignup.setObjectName("comboRoleSignup")
        self.comboRoleSignup.addItem("")
        self.comboRoleSignup.addItem("")
        self.gridSignup.addWidget(self.comboRoleSignup, 4, 1, 1, 1)
        self.btnSignup = QtWidgets.QPushButton(parent=self.tabSignup)
        self.btnSignup.setObjectName("btnSignup")
        self.gridSignup.addWidget(self.btnSignup, 5, 0, 1, 2)
        self.tabAuth.addTab(self.tabSignup, "")
        self.verticalLayout.addWidget(self.tabAuth)
        self.lblAuthStatus = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAuthStatus.setText("")
        self.lblAuthStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAuthStatus.setObjectName("lblAuthStatus")
        self.verticalLayout.addWidget(self.lblAuthStatus)
        self.verticalLayout.setStretch(1, 1)
        MainWindow_LoginSignUp.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow_LoginSignUp)
        self.statusbar.setObjectName("statusbar")
        MainWindow_LoginSignUp.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_LoginSignUp)
        self.tabAuth.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_LoginSignUp)

    def retranslateUi(self, MainWindow_LoginSignUp):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_LoginSignUp.setWindowTitle(_translate("MainWindow_LoginSignUp", "🍃 Fruit ML - Login / Sign Up"))
        self.lblTitle.setText(_translate("MainWindow_LoginSignUp", "🍎 Fruit ML Login / Sign Up"))
        self.lblUsernameLogin.setText(_translate("MainWindow_LoginSignUp", "Tên đăng nhập:"))
        self.lblPasswordLogin.setText(_translate("MainWindow_LoginSignUp", "Mật khẩu:"))
        self.lblRoleLogin.setText(_translate("MainWindow_LoginSignUp", "Vai trò:"))
        self.comboRoleLogin.setItemText(0, _translate("MainWindow_LoginSignUp", "User"))
        self.comboRoleLogin.setItemText(1, _translate("MainWindow_LoginSignUp", "Admin"))
        self.chkRemember.setText(_translate("MainWindow_LoginSignUp", "Ghi nhớ đăng nhập"))
        self.btnLogin.setText(_translate("MainWindow_LoginSignUp", "Đăng nhập"))
        self.btnForgotPassword.setText(_translate("MainWindow_LoginSignUp", "Quên mật khẩu?"))
        self.tabAuth.setTabText(self.tabAuth.indexOf(self.tabLogin), _translate("MainWindow_LoginSignUp", "Đăng nhập"))
        self.lblUsernameSignup.setText(_translate("MainWindow_LoginSignUp", "Tên đăng nhập:"))
        self.lblEmailSignup.setText(_translate("MainWindow_LoginSignUp", "Email:"))
        self.lblPasswordSignup.setText(_translate("MainWindow_LoginSignUp", "Mật khẩu:"))
        self.lblConfirmPassword.setText(_translate("MainWindow_LoginSignUp", "Nhập lại mật khẩu:"))
        self.lblRoleSignup.setText(_translate("MainWindow_LoginSignUp", "Vai trò:"))
        self.comboRoleSignup.setItemText(0, _translate("MainWindow_LoginSignUp", "User"))
        self.comboRoleSignup.setItemText(1, _translate("MainWindow_LoginSignUp", "Admin"))
        self.btnSignup.setText(_translate("MainWindow_LoginSignUp", "Đăng ký tài khoản"))
        self.tabAuth.setTabText(self.tabAuth.indexOf(self.tabSignup), _translate("MainWindow_LoginSignUp", "Đăng ký"))
