# Form implementation generated from reading ui file 'D:\TMĐT HK6\4.Machine learning\MLBA_FinalProjectt\final_ml\ui\ui_login_signup.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
# REDESIGNED: Modern Minimalist Green Theme
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_LoginSignUp(object):
    def setupUi(self, MainWindow_LoginSignUp):
        MainWindow_LoginSignUp.setObjectName("MainWindow_LoginSignUp")
        MainWindow_LoginSignUp.resize(800, 550)  # Giảm size xuống 800x550
        MainWindow_LoginSignUp.setStyleSheet("""
            /* Modern Minimalist Design System */
            QMainWindow {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #E8F5E9, stop:1 #F1F8F4);
            }
            
            QWidget {
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
                font-size: 14px;
                color: #1A3A2E;
            }
            
            /* Title Styles */
            QLabel#lblWelcome {
                font-size: 32px;
                font-weight: 700;
                color: #2D7A4E;
                letter-spacing: -0.5px;
                background: transparent;
            }
            
            QLabel#lblSubtitle {
                font-size: 13px;
                color: #5A7A6A;
                background: transparent;
                margin-top: 4px;
            }
            
            QLabel {
                color: #1A3A2E;
                font-weight: 500;
                font-size: 12px;
                background: transparent;
            }
            
            /* Card Container */
            QFrame#loginCard {
                background-color: white;
                border-radius: 16px;
                border: none;
            }
            
            /* Tab Widget */
            QTabWidget::pane {
                border: none;
                background: transparent;
                top: -1px;
            }
            
            QTabBar::tab {
                background: transparent;
                color: #8B9D94;
                border: none;
                border-bottom: 3px solid transparent;
                padding: 10px 24px;
                font-weight: 600;
                font-size: 14px;
                margin-right: 4px;
            }
            
            QTabBar::tab:selected {
                color: #2D7A4E;
                border-bottom-color: #2D7A4E;
            }
            
            QTabBar::tab:hover:!selected {
                color: #4A9B6B;
                background-color: #F8FAF9;
            }
            
            /* Input Fields */
            QLineEdit {
                border: 2px solid #E0E7E4;
                border-radius: 6px;
                padding: 9px 12px;
                background-color: #FFFFFF;
                font-size: 13px;
                color: #1A3A2E;
                min-height: 34px;
            }
            
            QLineEdit:focus {
                border-color: #2D7A4E;
                background-color: #FFFFFF;
            }
            
            QLineEdit:hover {
                border-color: #4A9B6B;
            }
            
            QLineEdit::placeholder {
                color: #8B9D94;
            }
            
            /* ComboBox */
            QComboBox {
                border: 2px solid #E0E7E4;
                border-radius: 6px;
                padding: 9px 12px;
                background-color: #FFFFFF;
                min-height: 34px;
                font-size: 13px;
            }
            
            QComboBox:hover {
                border-color: #4A9B6B;
            }
            
            QComboBox:focus {
                border-color: #2D7A4E;
            }
            
            QComboBox::drop-down {
                border: none;
                width: 30px;
            }
            
            QComboBox::down-arrow {
                image: none;
                border-left: 5px solid transparent;
                border-right: 5px solid transparent;
                border-top: 6px solid #5A7A6A;
            }
            
            QComboBox QAbstractItemView {
                background-color: white;
                border: 2px solid #E0E7E4;
                border-radius: 8px;
                selection-background-color: #E8F5E9;
                selection-color: #2D7A4E;
                padding: 4px;
            }
            
            /* Buttons */
            QPushButton {
                background-color: #2D7A4E;
                color: white;
                border: none;
                border-radius: 6px;
                padding: 10px 18px;
                font-size: 14px;
                font-weight: 600;
                min-height: 36px;
            }
            
            QPushButton:hover {
                background-color: #1E5435;
            }
            
            QPushButton:pressed {
                background-color: #1E5435;
            }
            
            QPushButton#btnForgotPassword {
                color: #2D7A4E;
                background: transparent;
                border: none;
                text-decoration: underline;
                padding: 8px;
                font-weight: 500;
                min-height: auto;
            }
            
            QPushButton#btnForgotPassword:hover {
                color: #1E5435;
                background: transparent;
            }
            
            /* Checkbox */
            QCheckBox {
                color: #1A3A2E;
                spacing: 6px;
                font-size: 12px;
            }
            
            QCheckBox::indicator {
                width: 16px;
                height: 16px;
                border: 2px solid #E0E7E4;
                border-radius: 3px;
                background-color: white;
            }
            
            QCheckBox::indicator:checked {
                background-color: #2D7A4E;
                border-color: #2D7A4E;
            }
            
            QCheckBox::indicator:hover {
                border-color: #4A9B6B;
            }
            
            /* Status Label */
            QLabel#lblAuthStatus {
                color: #E53935;
                font-weight: 600;
                font-size: 13px;
                background: transparent;
            }
            
            /* Scrollbar */
            QScrollBar:vertical {
                background-color: #F8FAF9;
                width: 10px;
                border-radius: 5px;
            }
            
            QScrollBar::handle:vertical {
                background-color: #E0E7E4;
                border-radius: 5px;
            }
            
            QScrollBar::handle:vertical:hover {
                background-color: #4A9B6B;
            }
        """)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_LoginSignUp)
        self.centralwidget.setObjectName("centralwidget")
        
        # Main horizontal layout to center the card
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(32, 32, 32, 32)
        self.mainLayout.setObjectName("mainLayout")
        
        # Left spacer
        spacerLeft = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.mainLayout.addItem(spacerLeft)
        
        # Login Card Container
        self.loginCard = QtWidgets.QFrame(parent=self.centralwidget)
        self.loginCard.setObjectName("loginCard")
        self.loginCard.setMinimumWidth(380)
        self.loginCard.setMaximumWidth(420)
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.loginCard)
        self.verticalLayout.setContentsMargins(32, 32, 32, 32)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # Welcome Section
        self.lblWelcome = QtWidgets.QLabel(parent=self.loginCard)
        self.lblWelcome.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblWelcome.setObjectName("lblWelcome")
        self.verticalLayout.addWidget(self.lblWelcome)
        
        self.lblSubtitle = QtWidgets.QLabel(parent=self.loginCard)
        self.lblSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.lblSubtitle.setWordWrap(True)
        self.verticalLayout.addWidget(self.lblSubtitle)
        
        # Spacer after title
        spacerTitle = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerTitle)
        
        # Tab Widget
        self.tabAuth = QtWidgets.QTabWidget(parent=self.loginCard)
        self.tabAuth.setObjectName("tabAuth")
        self.tabLogin = QtWidgets.QWidget()
        self.tabLogin.setObjectName("tabLogin")
        self.gridLogin = QtWidgets.QGridLayout(self.tabLogin)
        self.gridLogin.setContentsMargins(0, 16, 0, 0)
        self.gridLogin.setVerticalSpacing(10)
        self.gridLogin.setHorizontalSpacing(8)
        self.gridLogin.setObjectName("gridLogin")
        
        self.lblUsernameLogin = QtWidgets.QLabel(parent=self.tabLogin)
        self.lblUsernameLogin.setObjectName("lblUsernameLogin")
        self.gridLogin.addWidget(self.lblUsernameLogin, 0, 0, 1, 2)
        
        self.lineEditLoginUsername = QtWidgets.QLineEdit(parent=self.tabLogin)
        self.lineEditLoginUsername.setObjectName("lineEditLoginUsername")
        self.lineEditLoginUsername.setPlaceholderText("Nhập email hoặc tên đăng nhập")
        self.gridLogin.addWidget(self.lineEditLoginUsername, 1, 0, 1, 2)
        
        self.lblPasswordLogin = QtWidgets.QLabel(parent=self.tabLogin)
        self.lblPasswordLogin.setObjectName("lblPasswordLogin")
        self.gridLogin.addWidget(self.lblPasswordLogin, 2, 0, 1, 2)
        
        self.lineEditLoginPassword = QtWidgets.QLineEdit(parent=self.tabLogin)
        self.lineEditLoginPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditLoginPassword.setObjectName("lineEditLoginPassword")
        self.lineEditLoginPassword.setPlaceholderText("Nhập mật khẩu")
        self.gridLogin.addWidget(self.lineEditLoginPassword, 3, 0, 1, 2)
        
        self.lblRoleLogin = QtWidgets.QLabel(parent=self.tabLogin)
        self.lblRoleLogin.setObjectName("lblRoleLogin")
        self.gridLogin.addWidget(self.lblRoleLogin, 4, 0, 1, 2)
        
        self.comboRoleLogin = QtWidgets.QComboBox(parent=self.tabLogin)
        self.comboRoleLogin.setObjectName("comboRoleLogin")
        self.comboRoleLogin.addItem("")
        self.comboRoleLogin.addItem("")
        self.gridLogin.addWidget(self.comboRoleLogin, 5, 0, 1, 2)
        
        self.chkRemember = QtWidgets.QCheckBox(parent=self.tabLogin)
        self.chkRemember.setObjectName("chkRemember")
        self.gridLogin.addWidget(self.chkRemember, 6, 0, 1, 2)
        
        # Spacer before button
        spacerButton = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLogin.addItem(spacerButton, 7, 0, 1, 2)
        
        self.btnLogin = QtWidgets.QPushButton(parent=self.tabLogin)
        self.btnLogin.setObjectName("btnLogin")
        self.btnLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.gridLogin.addWidget(self.btnLogin, 8, 0, 1, 2)
        
        self.btnForgotPassword = QtWidgets.QPushButton(parent=self.tabLogin)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.btnForgotPassword.setFont(font)
        self.btnForgotPassword.setObjectName("btnForgotPassword")
        self.btnForgotPassword.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.gridLogin.addWidget(self.btnForgotPassword, 9, 0, 1, 2)
        self.tabAuth.addTab(self.tabLogin, "")
        self.tabSignup = QtWidgets.QWidget()
        self.tabSignup.setObjectName("tabSignup")
        self.gridSignup = QtWidgets.QGridLayout(self.tabSignup)
        self.gridSignup.setContentsMargins(0, 16, 0, 0)
        self.gridSignup.setVerticalSpacing(10)
        self.gridSignup.setHorizontalSpacing(8)
        self.gridSignup.setObjectName("gridSignup")
        
        self.lblUsernameSignup = QtWidgets.QLabel(parent=self.tabSignup)
        self.lblUsernameSignup.setObjectName("lblUsernameSignup")
        self.gridSignup.addWidget(self.lblUsernameSignup, 0, 0, 1, 2)
        
        self.lineEditSignupUsername = QtWidgets.QLineEdit(parent=self.tabSignup)
        self.lineEditSignupUsername.setObjectName("lineEditSignupUsername")
        self.lineEditSignupUsername.setPlaceholderText("Chọn tên đăng nhập")
        self.gridSignup.addWidget(self.lineEditSignupUsername, 1, 0, 1, 2)
        
        self.lblEmailSignup = QtWidgets.QLabel(parent=self.tabSignup)
        self.lblEmailSignup.setObjectName("lblEmailSignup")
        self.gridSignup.addWidget(self.lblEmailSignup, 2, 0, 1, 2)
        
        self.lineEditSignupEmail = QtWidgets.QLineEdit(parent=self.tabSignup)
        self.lineEditSignupEmail.setObjectName("lineEditSignupEmail")
        self.lineEditSignupEmail.setPlaceholderText("example@email.com")
        self.gridSignup.addWidget(self.lineEditSignupEmail, 3, 0, 1, 2)
        
        self.lblPasswordSignup = QtWidgets.QLabel(parent=self.tabSignup)
        self.lblPasswordSignup.setObjectName("lblPasswordSignup")
        self.gridSignup.addWidget(self.lblPasswordSignup, 4, 0, 1, 2)
        
        self.lineEditSignupPassword = QtWidgets.QLineEdit(parent=self.tabSignup)
        self.lineEditSignupPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditSignupPassword.setObjectName("lineEditSignupPassword")
        self.lineEditSignupPassword.setPlaceholderText("Tối thiểu 6 ký tự")
        self.gridSignup.addWidget(self.lineEditSignupPassword, 5, 0, 1, 2)
        
        self.lblConfirmPassword = QtWidgets.QLabel(parent=self.tabSignup)
        self.lblConfirmPassword.setObjectName("lblConfirmPassword")
        self.gridSignup.addWidget(self.lblConfirmPassword, 6, 0, 1, 2)
        
        self.lineEditSignupCFPassword = QtWidgets.QLineEdit(parent=self.tabSignup)
        self.lineEditSignupCFPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditSignupCFPassword.setObjectName("lineEditSignupCFPassword")
        self.lineEditSignupCFPassword.setPlaceholderText("Nhập lại mật khẩu")
        self.gridSignup.addWidget(self.lineEditSignupCFPassword, 7, 0, 1, 2)
        
        self.lblRoleSignup = QtWidgets.QLabel(parent=self.tabSignup)
        self.lblRoleSignup.setObjectName("lblRoleSignup")
        self.gridSignup.addWidget(self.lblRoleSignup, 8, 0, 1, 2)
        
        self.comboRoleSignup = QtWidgets.QComboBox(parent=self.tabSignup)
        self.comboRoleSignup.setObjectName("comboRoleSignup")
        self.comboRoleSignup.addItem("")
        self.comboRoleSignup.addItem("")
        self.gridSignup.addWidget(self.comboRoleSignup, 9, 0, 1, 2)
        
        # Spacer before button
        spacerSignup = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridSignup.addItem(spacerSignup, 10, 0, 1, 2)
        
        self.btnSignup = QtWidgets.QPushButton(parent=self.tabSignup)
        self.btnSignup.setObjectName("btnSignup")
        self.btnSignup.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.gridSignup.addWidget(self.btnSignup, 11, 0, 1, 2)
        self.tabAuth.addTab(self.tabSignup, "")
        self.verticalLayout.addWidget(self.tabAuth)
        
        self.lblAuthStatus = QtWidgets.QLabel(parent=self.loginCard)
        self.lblAuthStatus.setText("")
        self.lblAuthStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblAuthStatus.setObjectName("lblAuthStatus")
        self.verticalLayout.addWidget(self.lblAuthStatus)
        
        # Add card to main layout
        self.mainLayout.addWidget(self.loginCard)
        
        # Right spacer
        spacerRight = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.mainLayout.addItem(spacerRight)
        
        MainWindow_LoginSignUp.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow_LoginSignUp)
        self.statusbar.setObjectName("statusbar")
        self.statusbar.setStyleSheet("background: white; border-top: 2px solid #E0E7E4; color: #5A7A6A;")
        MainWindow_LoginSignUp.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_LoginSignUp)
        self.tabAuth.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_LoginSignUp)

    def retranslateUi(self, MainWindow_LoginSignUp):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_LoginSignUp.setWindowTitle(_translate("MainWindow_LoginSignUp", "🍃 Fruit ML - Authentication"))
        self.lblWelcome.setText(_translate("MainWindow_LoginSignUp", "Fruit ML"))
        self.lblSubtitle.setText(_translate("MainWindow_LoginSignUp", "Hệ thống phân loại chất lượng trái cây thông minh"))
        self.lblUsernameLogin.setText(_translate("MainWindow_LoginSignUp", "Tên đăng nhập hoặc Email"))
        self.lblPasswordLogin.setText(_translate("MainWindow_LoginSignUp", "Mật khẩu"))
        self.lblRoleLogin.setText(_translate("MainWindow_LoginSignUp", "Vai trò"))
        self.comboRoleLogin.setItemText(0, _translate("MainWindow_LoginSignUp", "User"))
        self.comboRoleLogin.setItemText(1, _translate("MainWindow_LoginSignUp", "Admin"))
        self.chkRemember.setText(_translate("MainWindow_LoginSignUp", "Ghi nhớ đăng nhập"))
        self.btnLogin.setText(_translate("MainWindow_LoginSignUp", "Đăng nhập"))
        self.btnForgotPassword.setText(_translate("MainWindow_LoginSignUp", "Quên mật khẩu?"))
        self.tabAuth.setTabText(self.tabAuth.indexOf(self.tabLogin), _translate("MainWindow_LoginSignUp", "Đăng nhập"))
        self.lblUsernameSignup.setText(_translate("MainWindow_LoginSignUp", "Tên đăng nhập"))
        self.lblEmailSignup.setText(_translate("MainWindow_LoginSignUp", "Email"))
        self.lblPasswordSignup.setText(_translate("MainWindow_LoginSignUp", "Mật khẩu"))
        self.lblConfirmPassword.setText(_translate("MainWindow_LoginSignUp", "Xác nhận mật khẩu"))
        self.lblRoleSignup.setText(_translate("MainWindow_LoginSignUp", "Vai trò"))
        self.comboRoleSignup.setItemText(0, _translate("MainWindow_LoginSignUp", "User"))
        self.comboRoleSignup.setItemText(1, _translate("MainWindow_LoginSignUp", "Admin"))
        self.btnSignup.setText(_translate("MainWindow_LoginSignUp", "Tạo tài khoản"))
        self.tabAuth.setTabText(self.tabAuth.indexOf(self.tabSignup), _translate("MainWindow_LoginSignUp", "Đăng ký"))
